In [22]:
import torch
import torch.nn.functional as F

In [33]:
batch = 100
N = 3
Wr = torch.randn(N, N)
b = torch.randn(batch, N)
a = torch.randn(batch, N)
A = torch.eye(N) - Wr + torch.diag_embed(a) @ Wr

print(A.shape)

soln = torch.linalg.solve(A, b)
print(soln[0, :])

torch.Size([100, 3, 3])
tensor([ 2.5693,  1.8255, -0.4162])


In [34]:
# This is what is desired
batch_idx = 0
b1 = b[batch_idx, :]
a1 = a[batch_idx, :]
A1 = (torch.eye(N) - Wr + torch.diag(a1) @ Wr)
print(torch.linalg.solve(A1, b1))

tensor([ 2.5693,  1.8255, -0.4162])


In [31]:
torch.diag(a1) @ Wr

tensor([[-0.4853,  0.0521,  1.3268],
        [-0.4169,  0.2515, -0.0754],
        [-1.1647,  0.2337,  0.2233]])

In [32]:
F.linear(torch.diag_embed(a), Wr)[0]

tensor([[-0.4853, -1.2070, -0.9957],
        [ 0.0180,  0.2515,  0.0690],
        [ 1.5520, -0.2554,  0.2233]])